### ISSUE TITLE
Payout status to reflect the transaction status according to Insight

### ISSUE THREAD

**Issue by rashagen** [satoshipay/satoshipay.github.io#22]
The below "Paid Out" status is confusing (tx was still being verified on the blockchain)

<img width="1026" alt="screen shot 2015-12-16 at 10 13 09" src="https://cloud.githubusercontent.com/assets/1915920/11837815/8b0aaf2e-a3e3-11e5-93ff-16889289fb13.png">

**Comment by Levino** [comment]
Cannot be changed for some time.

**Comment by rashagen** [comment]
Wrong repo. Closing.
