### ISSUE TITLE
add directory listing to terms of service

### ISSUE THREAD

**Issue by meinharrd** [satoshipay/satoshipay.github.io#26]
we will list publishers in a public directory at a later point - to show where you can spend (or earn) satoshis. we should ask for permission to do this. because the directory does not exist yet, we only need to prepare this in the terms and not worry about people wanting to opt-out yet.

@Flotob could you please add a section to the terms regarding this?

also see https://github.com/satoshipay/nano-dashboard/issues/176

**Comment by rashagen** [comment]
@rashagen reminder: add Doge sprint to milestone

**Comment by Flotob** [comment]
![bildschirmfoto 2016-01-13 um 13 17 39](https://cloud.githubusercontent.com/assets/184569/12294104/0f64d7c0-b9f8-11e5-8c58-0d05350c4784.png)

Added to ToS and sent you a PR @meinharrd
