### ISSUE TITLE
add press page

### ISSUE THREAD

**Issue by meinharrd** [satoshipay/satoshipay.github.io#29]
content:
 - recent relevant press coverage (julia has a list)
 - logos
 - press contact (hello@satoshipay.io)

other requirements:
 - link at bottom of satoshipay.io in front of "FAQ"
 - url: satoshipay.io/press (.html not needed, see #28)

examples:
 - https://www.coinbase.com/press
 - https://www.kraken.com/about/press
 - https://bitpay.com/about/press
 - https://www.bitbond.com/press

**Comment by Levino** [comment]
@meinharrd This is public. Do you acknowledge?

**Comment by meinharrd** [comment]
@rashagen some notes:

 - not sure i like the 2 columns, i like kraken's and bitbond's flat list, easy to scan for certain dates
 - no logo without "SatoshiPay" please. also offer pdf or eps download, white on black, inverted and maybe black on transparent background?
 - please reduce news articles to 1 or max. 2 per news event
 - no regulatory announcements please, just actual press people writing
 - videos out (for now, can go to a different section later)
 - click on satoshipay logo at the top does not bring me back to the homepage, some jquery error?
